"""initial schema from dump

Revision ID: 8b824433eb56
Revises: 
Create Date: 2026-04-03 13:19:15.321401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b824433eb56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('op_name_of_sample',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ref_days_of_the_week',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('op_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_of_sample_id', sa.Integer(), nullable=True),
    sa.Column('day_of_week_id', sa.Integer(), nullable=True),
    sa.Column('time_slot_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('audience_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['audience_id'], ['ref_audiences.id'], ),
    sa.ForeignKeyConstraint(['day_of_week_id'], ['ref_days_of_the_week.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['op_lessons.id'], ),
    sa.ForeignKeyConstraint(['name_of_sample_id'], ['op_name_of_sample.id'], ),
    sa.ForeignKeyConstraint(['time_slot_id'], ['ref_time_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('op_teacher_users')
    op.drop_table('op_audiences_of_pairs')
    op.drop_table('op_teacher_work_windows')
    op.drop_table('op_user_roles')
    op.drop_table('op_user_activity_logs')
    op.drop_table('op_teachers_groups')
    op.drop_table('op_schedule_items')
    op.drop_table('op_role_permissions')
    op.drop_table('op_insertions')
    op.drop_table('op_audiences_of_subdivisions')
    op.drop_table('op_user_faculties')
    op.alter_column('op_final_schedule', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('op_final_schedule', 'time_slot_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('op_final_schedule', 'audience_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('op_final_schedule', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_index(op.f('idx_final_schedule_date'), table_name='op_final_schedule')
    op.drop_constraint(op.f('fk_final_lesson'), 'op_final_schedule', type_='foreignkey')
    op.create_foreign_key(None, 'op_final_schedule', 'op_lessons', ['lesson_id'], ['id'])
    op.alter_column('op_groups_of_pairs', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('op_groups_of_pairs', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('op_lessons_ref_subject_fk'), 'op_lessons', type_='foreignkey')
    op.drop_constraint(op.f('op_lessons_time_slot_id_fkey'), 'op_lessons', type_='foreignkey')
    op.drop_constraint(op.f('op_lessons_insertion_id_fkey'), 'op_lessons', type_='foreignkey')
    op.create_foreign_key(None, 'op_lessons', 'ref_subject', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'op_lessons', 'ref_time_slots', ['time_slot_id'], ['id'])
    op.drop_column('op_lessons', 'text')
    op.drop_column('op_lessons', 'week_day')
    op.drop_column('op_lessons', 'type')
    op.drop_column('op_lessons', 'insertion_id')
    op.alter_column('op_schedule_items_1', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('op_schedule_items_1', 'time_slot_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('op_schedule_items_1', 'audience_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('op_schedule_items_1', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('op_schedule_items_1', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('op_schedule_items_1', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('op_teachers_of_pairs', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('op_teachers_of_pairs', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('ref_audiences_building_id_fkey'), 'ref_audiences', type_='foreignkey')
    op.create_foreign_key(None, 'ref_audiences', 'ref_buildings', ['building_id'], ['id'])
    op.drop_column('ref_audiences', 'autocreated')
    op.create_unique_constraint(None, 'ref_calendar', ['date'])
    op.drop_constraint(op.f('ref_groups_faculty_id_fkey'), 'ref_groups', type_='foreignkey')
    op.create_foreign_key(None, 'ref_groups', 'ref_faculties', ['faculty_id'], ['id'])
    op.alter_column('ref_subject', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'ref_teachers', ['login'])
    op.drop_column('ref_teachers', 'max_hours_per_week')
    op.drop_column('ref_teachers', 'max_hours_per_day')
    op.drop_constraint(op.f('ref_users_user_type_id_fkey'), 'ref_users', type_='foreignkey')
    op.create_foreign_key(None, 'ref_users', 'ref_user_types', ['user_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ref_users', type_='foreignkey')
    op.create_foreign_key(op.f('ref_users_user_type_id_fkey'), 'ref_users', 'ref_user_types', ['user_type_id'], ['id'], deferrable=True)
    op.add_column('ref_teachers', sa.Column('max_hours_per_day', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ref_teachers', sa.Column('max_hours_per_week', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ref_teachers', type_='unique')
    op.alter_column('ref_subject', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'ref_groups', type_='foreignkey')
    op.create_foreign_key(op.f('ref_groups_faculty_id_fkey'), 'ref_groups', 'ref_faculties', ['faculty_id'], ['id'], deferrable=True)
    op.drop_constraint(None, 'ref_calendar', type_='unique')
    op.add_column('ref_audiences', sa.Column('autocreated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ref_audiences', type_='foreignkey')
    op.create_foreign_key(op.f('ref_audiences_building_id_fkey'), 'ref_audiences', 'ref_buildings', ['building_id'], ['id'], deferrable=True)
    op.alter_column('op_teachers_of_pairs', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('op_teachers_of_pairs', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('op_schedule_items_1', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('op_schedule_items_1', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('op_schedule_items_1', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('op_schedule_items_1', 'audience_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('op_schedule_items_1', 'time_slot_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('op_schedule_items_1', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('op_lessons', sa.Column('insertion_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('op_lessons', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('op_lessons', sa.Column('week_day', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('op_lessons', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'op_lessons', type_='foreignkey')
    op.drop_constraint(None, 'op_lessons', type_='foreignkey')
    op.create_foreign_key(op.f('op_lessons_insertion_id_fkey'), 'op_lessons', 'op_insertions', ['insertion_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('op_lessons_time_slot_id_fkey'), 'op_lessons', 'ref_time_slots', ['time_slot_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('op_lessons_ref_subject_fk'), 'op_lessons', 'ref_subject', ['id'], ['id'])
    op.alter_column('op_groups_of_pairs', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('op_groups_of_pairs', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'op_final_schedule', type_='foreignkey')
    op.create_foreign_key(op.f('fk_final_lesson'), 'op_final_schedule', 'op_lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_final_schedule_date'), 'op_final_schedule', ['date'], unique=False)
    op.alter_column('op_final_schedule', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('op_final_schedule', 'audience_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('op_final_schedule', 'time_slot_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('op_final_schedule', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('op_user_faculties',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('faculty_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('access_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['ref_faculties.id'], name=op.f('op_user_faculties_faculty_id_fkey'), deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ref_users.id'], name=op.f('op_user_faculties_user_id_fkey'), deferrable=True)
    )
    op.create_table('op_audiences_of_subdivisions',
    sa.Column('audience_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subdivision_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['audience_id'], ['ref_audiences.id'], name=op.f('op_audiences_of_subdivisions_audience_id_fkey'), deferrable=True),
    sa.ForeignKeyConstraint(['subdivision_id'], ['ref_subdivisions.id'], name=op.f('op_audiences_of_subdivisions_subdivision_id_fkey'), deferrable=True)
    )
    op.create_table('op_insertions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('faculty_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['ref_faculties.id'], name=op.f('op_insertions_faculty_id_fkey'), deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('op_insertions_pkey'))
    )
    op.create_table('op_role_permissions',
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('granted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('granted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['ref_users.id'], name=op.f('op_role_permissions_granted_by_fkey'), deferrable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['ref_permissions.id'], name=op.f('op_role_permissions_permission_id_fkey'), deferrable=True),
    sa.ForeignKeyConstraint(['role_id'], ['ref_roles.id'], name=op.f('op_role_permissions_role_id_fkey'), deferrable=True)
    )
    op.create_table('op_schedule_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_slot_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('audience_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_pinned', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['audience_id'], ['ref_audiences.id'], name=op.f('op_schedule_items_audience_id_fkey'), deferrable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['op_lessons.id'], name=op.f('op_schedule_items_lesson_id_fkey'), deferrable=True),
    sa.ForeignKeyConstraint(['time_slot_id'], ['ref_time_slots.id'], name=op.f('op_schedule_items_time_slot_id_fkey'), deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('op_schedule_items_pkey'))
    )
    op.create_table('op_teachers_groups',
    sa.Column('teachers_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('groups_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['groups_id'], ['ref_groups.id'], name=op.f('op_teachers_groups_ref_groups_fk')),
    sa.ForeignKeyConstraint(['teachers_id'], ['ref_teachers.id'], name=op.f('op_teachers_groups_ref_teachers_fk'))
    )
    op.create_table('op_user_activity_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ref_users.id'], name=op.f('op_user_activity_logs_user_id_fkey'), deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('op_user_activity_logs_pkey'))
    )
    op.create_table('op_user_roles',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assigned_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assigned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['ref_users.id'], name=op.f('op_user_roles_assigned_by_fkey'), deferrable=True),
    sa.ForeignKeyConstraint(['role_id'], ['ref_roles.id'], name=op.f('op_user_roles_role_id_fkey'), deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ref_users.id'], name=op.f('op_user_roles_user_id_fkey'), deferrable=True)
    )
    op.create_table('op_teacher_work_windows',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['ref_teachers.id'], name=op.f('op_teacher_work_windows_teacher_id_fkey'), deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('op_teacher_work_windows_pkey'))
    )
    op.create_table('op_audiences_of_pairs',
    sa.Column('audience_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['audience_id'], ['ref_audiences.id'], name=op.f('op_audiences_of_pairs_ref_audiences_fk')),
    sa.ForeignKeyConstraint(['subject_id'], ['ref_subject.id'], name=op.f('op_audiences_of_pairs_ref_subject_fk'))
    )
    op.create_table('op_teacher_users',
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['ref_teachers.id'], name=op.f('op_teacher_users_teacher_id_fkey'), deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ref_users.id'], name=op.f('op_teacher_users_user_id_fkey'), deferrable=True),
    sa.UniqueConstraint('teacher_id', name=op.f('op_teacher_users_teacher_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_id', name=op.f('op_teacher_users_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('op_templates')
    op.drop_table('ref_days_of_the_week')
    op.drop_table('op_name_of_sample')
    # ### end Alembic commands ###
