"""add autoincrement to ids

Revision ID: 531d809f3d3f
Revises: 8df055f089b1
Create Date: 2026-03-25 11:26:40.461813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '531d809f3d3f'
down_revision: Union[str, Sequence[str], None] = '8df055f089b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('op_groups_of_pairs_lesson_id_fkey'), 'op_groups_of_pairs', type_='foreignkey')
    op.drop_constraint(op.f('op_schedule_items_time_slot_id_fkey'), 'op_schedule_items', type_='foreignkey')
    op.drop_constraint(op.f('op_schedule_items_lesson_id_fkey'), 'op_schedule_items', type_='foreignkey')
    op.drop_constraint(op.f('ref_audiences_building_id_fkey'), 'ref_audiences', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('ref_audiences_building_id_fkey'), 'ref_audiences', 'ref_buildings', ['building_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('op_schedule_items_lesson_id_fkey'), 'op_schedule_items', 'op_lessons', ['lesson_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('op_schedule_items_time_slot_id_fkey'), 'op_schedule_items', 'ref_time_slots', ['time_slot_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('op_groups_of_pairs_lesson_id_fkey'), 'op_groups_of_pairs', 'op_lessons', ['lesson_id'], ['id'], deferrable=True)
    # ### end Alembic commands ###
