"""fix group id autoincrement

Revision ID: 8df055f089b1
Revises: 
Create Date: 2026-03-25 09:57:13.926282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8df055f089b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('op_audiences_of_pairs', 'audience_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('op_audiences_of_pairs', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('op_audiences_of_pairs_audience_id_fkey'), 'op_audiences_of_pairs', type_='foreignkey')
    op.drop_constraint(op.f('op_audiences_of_pairs_lesson_id_fkey'), 'op_audiences_of_pairs', type_='foreignkey')
    op.create_foreign_key(None, 'op_audiences_of_pairs', 'ref_audiences', ['audience_id'], ['id'])
    op.create_foreign_key(None, 'op_audiences_of_pairs', 'op_lessons', ['lesson_id'], ['id'])
    op.alter_column('op_audiences_of_subdivisions', 'audience_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('op_audiences_of_subdivisions', 'subdivision_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('op_audiences_of_subdivisions_audience_id_fkey'), 'op_audiences_of_subdivisions', type_='foreignkey')
    op.drop_constraint(op.f('op_audiences_of_subdivisions_subdivision_id_fkey'), 'op_audiences_of_subdivisions', type_='foreignkey')
    op.create_foreign_key(None, 'op_audiences_of_subdivisions', 'ref_audiences', ['audience_id'], ['id'])
    op.create_foreign_key(None, 'op_audiences_of_subdivisions', 'ref_subdivisions', ['subdivision_id'], ['id'])
    op.alter_column('op_groups_of_pairs', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('op_groups_of_pairs', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('op_groups_of_pairs_lesson_id_fkey1'), 'op_groups_of_pairs', type_='foreignkey')
    op.drop_constraint(op.f('op_groups_of_pairs_group_id_fkey'), 'op_groups_of_pairs', type_='foreignkey')
    op.create_foreign_key(None, 'op_groups_of_pairs', 'op_lessons', ['lesson_id'], ['id'])
    op.create_foreign_key(None, 'op_groups_of_pairs', 'ref_groups', ['group_id'], ['id'])
    op.drop_constraint(op.f('op_insertions_faculty_id_fkey'), 'op_insertions', type_='foreignkey')
    op.create_foreign_key(None, 'op_insertions', 'ref_faculties', ['faculty_id'], ['id'])
    op.drop_constraint(op.f('op_lessons_time_slot_id_fkey'), 'op_lessons', type_='foreignkey')
    op.drop_constraint(op.f('op_lessons_insertion_id_fkey'), 'op_lessons', type_='foreignkey')
    op.create_foreign_key(None, 'op_lessons', 'ref_time_slots', ['time_slot_id'], ['id'])
    op.create_foreign_key(None, 'op_lessons', 'op_insertions', ['insertion_id'], ['id'])
    op.alter_column('op_role_permissions', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('op_role_permissions', 'permission_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('op_role_permissions_role_id_fkey'), 'op_role_permissions', type_='foreignkey')
    op.drop_constraint(op.f('op_role_permissions_permission_id_fkey'), 'op_role_permissions', type_='foreignkey')
    op.drop_constraint(op.f('op_role_permissions_granted_by_fkey'), 'op_role_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'op_role_permissions', 'ref_roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'op_role_permissions', 'ref_permissions', ['permission_id'], ['id'])
    op.create_foreign_key(None, 'op_role_permissions', 'ref_users', ['granted_by'], ['id'])
    op.drop_constraint(op.f('op_schedule_items_audience_id_fkey'), 'op_schedule_items', type_='foreignkey')
    op.drop_constraint(op.f('op_schedule_items_time_slot_id_fkey1'), 'op_schedule_items', type_='foreignkey')
    op.drop_constraint(op.f('op_schedule_items_lesson_id_fkey1'), 'op_schedule_items', type_='foreignkey')
    op.create_foreign_key(None, 'op_schedule_items', 'ref_audiences', ['audience_id'], ['id'])
    op.create_foreign_key(None, 'op_schedule_items', 'ref_time_slots', ['time_slot_id'], ['id'])
    op.create_foreign_key(None, 'op_schedule_items', 'op_lessons', ['lesson_id'], ['id'])
    op.alter_column('op_teacher_users', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('op_teacher_users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('op_teacher_users_user_id_fkey'), 'op_teacher_users', type_='foreignkey')
    op.drop_constraint(op.f('op_teacher_users_teacher_id_fkey'), 'op_teacher_users', type_='foreignkey')
    op.create_foreign_key(None, 'op_teacher_users', 'ref_users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'op_teacher_users', 'ref_teachers', ['teacher_id'], ['id'])
    op.drop_constraint(op.f('op_teacher_work_windows_teacher_id_fkey'), 'op_teacher_work_windows', type_='foreignkey')
    op.create_foreign_key(None, 'op_teacher_work_windows', 'ref_teachers', ['teacher_id'], ['id'])
    op.alter_column('op_teachers_of_pairs', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('op_teachers_of_pairs', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('op_teachers_of_pairs_lesson_id_fkey'), 'op_teachers_of_pairs', type_='foreignkey')
    op.drop_constraint(op.f('op_teachers_of_pairs_teacher_id_fkey'), 'op_teachers_of_pairs', type_='foreignkey')
    op.create_foreign_key(None, 'op_teachers_of_pairs', 'op_lessons', ['lesson_id'], ['id'])
    op.create_foreign_key(None, 'op_teachers_of_pairs', 'ref_teachers', ['teacher_id'], ['id'])
    op.drop_constraint(op.f('op_user_activity_logs_user_id_fkey'), 'op_user_activity_logs', type_='foreignkey')
    op.create_foreign_key(None, 'op_user_activity_logs', 'ref_users', ['user_id'], ['id'])
    op.alter_column('op_user_faculties', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('op_user_faculties', 'faculty_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('op_user_faculties_user_id_fkey'), 'op_user_faculties', type_='foreignkey')
    op.drop_constraint(op.f('op_user_faculties_faculty_id_fkey'), 'op_user_faculties', type_='foreignkey')
    op.create_foreign_key(None, 'op_user_faculties', 'ref_users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'op_user_faculties', 'ref_faculties', ['faculty_id'], ['id'])
    op.alter_column('op_user_roles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('op_user_roles', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('op_user_roles_role_id_fkey'), 'op_user_roles', type_='foreignkey')
    op.drop_constraint(op.f('op_user_roles_assigned_by_fkey'), 'op_user_roles', type_='foreignkey')
    op.drop_constraint(op.f('op_user_roles_user_id_fkey'), 'op_user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'op_user_roles', 'ref_roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'op_user_roles', 'ref_users', ['assigned_by'], ['id'])
    op.create_foreign_key(None, 'op_user_roles', 'ref_users', ['user_id'], ['id'])
    op.drop_constraint(op.f('ref_audiences_building_id_fkey1'), 'ref_audiences', type_='foreignkey')
    op.create_foreign_key(None, 'ref_audiences', 'ref_buildings', ['building_id'], ['id'])
    op.drop_constraint(op.f('ref_groups_faculty_id_fkey'), 'ref_groups', type_='foreignkey')
    op.create_foreign_key(None, 'ref_groups', 'ref_faculties', ['faculty_id'], ['id'])
    op.create_unique_constraint(None, 'ref_teachers', ['login'])
    op.alter_column('ref_user_types', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('ref_users_user_type_id_fkey'), 'ref_users', type_='foreignkey')
    op.create_foreign_key(None, 'ref_users', 'ref_user_types', ['user_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ref_users', type_='foreignkey')
    op.create_foreign_key(op.f('ref_users_user_type_id_fkey'), 'ref_users', 'ref_user_types', ['user_type_id'], ['id'], deferrable=True)
    op.alter_column('ref_user_types', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'ref_teachers', type_='unique')
    op.drop_constraint(None, 'ref_groups', type_='foreignkey')
    op.create_foreign_key(op.f('ref_groups_faculty_id_fkey'), 'ref_groups', 'ref_faculties', ['faculty_id'], ['id'], deferrable=True)
    op.drop_constraint(None, 'ref_audiences', type_='foreignkey')
    op.create_foreign_key(op.f('ref_audiences_building_id_fkey1'), 'ref_audiences', 'ref_buildings', ['building_id'], ['id'], deferrable=True)
    op.drop_constraint(None, 'op_user_roles', type_='foreignkey')
    op.drop_constraint(None, 'op_user_roles', type_='foreignkey')
    op.drop_constraint(None, 'op_user_roles', type_='foreignkey')
    op.create_foreign_key(op.f('op_user_roles_user_id_fkey'), 'op_user_roles', 'ref_users', ['user_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('op_user_roles_assigned_by_fkey'), 'op_user_roles', 'ref_users', ['assigned_by'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('op_user_roles_role_id_fkey'), 'op_user_roles', 'ref_roles', ['role_id'], ['id'], deferrable=True)
    op.alter_column('op_user_roles', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('op_user_roles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'op_user_faculties', type_='foreignkey')
    op.drop_constraint(None, 'op_user_faculties', type_='foreignkey')
    op.create_foreign_key(op.f('op_user_faculties_faculty_id_fkey'), 'op_user_faculties', 'ref_faculties', ['faculty_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('op_user_faculties_user_id_fkey'), 'op_user_faculties', 'ref_users', ['user_id'], ['id'], deferrable=True)
    op.alter_column('op_user_faculties', 'faculty_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('op_user_faculties', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'op_user_activity_logs', type_='foreignkey')
    op.create_foreign_key(op.f('op_user_activity_logs_user_id_fkey'), 'op_user_activity_logs', 'ref_users', ['user_id'], ['id'], deferrable=True)
    op.drop_constraint(None, 'op_teachers_of_pairs', type_='foreignkey')
    op.drop_constraint(None, 'op_teachers_of_pairs', type_='foreignkey')
    op.create_foreign_key(op.f('op_teachers_of_pairs_teacher_id_fkey'), 'op_teachers_of_pairs', 'ref_teachers', ['teacher_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('op_teachers_of_pairs_lesson_id_fkey'), 'op_teachers_of_pairs', 'op_lessons', ['lesson_id'], ['id'], deferrable=True)
    op.alter_column('op_teachers_of_pairs', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('op_teachers_of_pairs', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'op_teacher_work_windows', type_='foreignkey')
    op.create_foreign_key(op.f('op_teacher_work_windows_teacher_id_fkey'), 'op_teacher_work_windows', 'ref_teachers', ['teacher_id'], ['id'], deferrable=True)
    op.drop_constraint(None, 'op_teacher_users', type_='foreignkey')
    op.drop_constraint(None, 'op_teacher_users', type_='foreignkey')
    op.create_foreign_key(op.f('op_teacher_users_teacher_id_fkey'), 'op_teacher_users', 'ref_teachers', ['teacher_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('op_teacher_users_user_id_fkey'), 'op_teacher_users', 'ref_users', ['user_id'], ['id'], deferrable=True)
    op.alter_column('op_teacher_users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('op_teacher_users', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'op_schedule_items', type_='foreignkey')
    op.drop_constraint(None, 'op_schedule_items', type_='foreignkey')
    op.drop_constraint(None, 'op_schedule_items', type_='foreignkey')
    op.create_foreign_key(op.f('op_schedule_items_lesson_id_fkey1'), 'op_schedule_items', 'op_lessons', ['lesson_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('op_schedule_items_time_slot_id_fkey1'), 'op_schedule_items', 'ref_time_slots', ['time_slot_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('op_schedule_items_audience_id_fkey'), 'op_schedule_items', 'ref_audiences', ['audience_id'], ['id'], deferrable=True)
    op.drop_constraint(None, 'op_role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'op_role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'op_role_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('op_role_permissions_granted_by_fkey'), 'op_role_permissions', 'ref_users', ['granted_by'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('op_role_permissions_permission_id_fkey'), 'op_role_permissions', 'ref_permissions', ['permission_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('op_role_permissions_role_id_fkey'), 'op_role_permissions', 'ref_roles', ['role_id'], ['id'], deferrable=True)
    op.alter_column('op_role_permissions', 'permission_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('op_role_permissions', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'op_lessons', type_='foreignkey')
    op.drop_constraint(None, 'op_lessons', type_='foreignkey')
    op.create_foreign_key(op.f('op_lessons_insertion_id_fkey'), 'op_lessons', 'op_insertions', ['insertion_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('op_lessons_time_slot_id_fkey'), 'op_lessons', 'ref_time_slots', ['time_slot_id'], ['id'], deferrable=True)
    op.drop_constraint(None, 'op_insertions', type_='foreignkey')
    op.create_foreign_key(op.f('op_insertions_faculty_id_fkey'), 'op_insertions', 'ref_faculties', ['faculty_id'], ['id'], deferrable=True)
    op.drop_constraint(None, 'op_groups_of_pairs', type_='foreignkey')
    op.drop_constraint(None, 'op_groups_of_pairs', type_='foreignkey')
    op.create_foreign_key(op.f('op_groups_of_pairs_group_id_fkey'), 'op_groups_of_pairs', 'ref_groups', ['group_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('op_groups_of_pairs_lesson_id_fkey1'), 'op_groups_of_pairs', 'op_lessons', ['lesson_id'], ['id'], deferrable=True)
    op.alter_column('op_groups_of_pairs', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('op_groups_of_pairs', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'op_audiences_of_subdivisions', type_='foreignkey')
    op.drop_constraint(None, 'op_audiences_of_subdivisions', type_='foreignkey')
    op.create_foreign_key(op.f('op_audiences_of_subdivisions_subdivision_id_fkey'), 'op_audiences_of_subdivisions', 'ref_subdivisions', ['subdivision_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('op_audiences_of_subdivisions_audience_id_fkey'), 'op_audiences_of_subdivisions', 'ref_audiences', ['audience_id'], ['id'], deferrable=True)
    op.alter_column('op_audiences_of_subdivisions', 'subdivision_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('op_audiences_of_subdivisions', 'audience_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'op_audiences_of_pairs', type_='foreignkey')
    op.drop_constraint(None, 'op_audiences_of_pairs', type_='foreignkey')
    op.create_foreign_key(op.f('op_audiences_of_pairs_lesson_id_fkey'), 'op_audiences_of_pairs', 'op_lessons', ['lesson_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('op_audiences_of_pairs_audience_id_fkey'), 'op_audiences_of_pairs', 'ref_audiences', ['audience_id'], ['id'], deferrable=True)
    op.alter_column('op_audiences_of_pairs', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('op_audiences_of_pairs', 'audience_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
